### ISSUE TITLE
Project is not necessarily best place for documentation

### ISSUE THREAD

**Issue by jhrabi** [admpresales/script-directory#1]
@panama69 Trying to use a project as a documentation point has issues, since this project continually moves down the based upon when it's been updated last. If this is going to be a permanent project, perhaps using the wiki section would be better, to separate the document into appropriate parts.

The naming of the project also doesn't necessarily dictate that it is a documentation project and not anything else. Perhaps a name change (script-guide) or something else might be a better naming convention.

**Comment by panama69** [comment]
@jhrabi  You will notice that it is pinned when you go to https://github.com/admpresales (a new feature) so this way it will be easily seen at the top level even if the project "scrolls off the bottom".

A wiki would be nice but the Readme is the first think that is shown when you go into the project wich is better and easier than teaching people to click on the Wiki tab to see the info.

I like the "script-guide".  I thought "script-directory" was more explicit but I can easily be swayed to "script-guide" if you think that is better name than "script-directory"

**Comment by panama69** [comment]
@jhrabi i am still working through cleaning up the current content but if there are other things you think should be added, let me know.

**Comment by jhrabi** [comment]
@panama69 For some reason, I thought pinning was per user, not repository wide (just saw you pinned it now). So that fixes the first issue. I can come up with a better name then script-guide, but I think script-directory makes you think there's some assets in it. I'll give it some thought

**Comment by panama69** [comment]
@jhrabi I thought so too.  so after i added it, I then pinned it and had shahar login to see if it was pinned for him.  and it was.  The question I don't know is if anyone can pin or if you and i an because of our role.

**Comment by jhrabi** [comment]
@panama69 I'm hoping only admins can pin. I'll look through the documentation and see. I added a description to it show it shows up in the pinned info as well. Might want something like "Read Me First!" or something to grab people's attention
